### ISSUE TITLE
`ecdsa.GenerateKey()` panics for tests on updating versions in go.mod file

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#1119]
### Description

In tests, to generate a dummy private key for getting transaction signer we follow 
```
privateKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
txnOpts, _ := bind.NewKeyedTransactorWithChainID(privateKey, big.NewInt(31337))
```
  
On updating the go version to `go1.21.1` in `go.mod` file and updating the  dependencies to corresponding updates, tests where failing with error 

```
panic: crypto/elliptic: attempted operation on invalid point [recovered] panic: crypto/elliptic: attempted operation on invalid point
``` 
It is failing due to added security in the updated `go-ethereum` version that if the point does not lie on elliptic curve then it panics. 
There is a panic with the above error if the curve instance is not of curve `secp256k1`

### Solution
Here in this part of the code, changing curve instance to `crypto.S256()` instead of `elliptic.P256()` should work.
 ```
privateKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
```

Change it to - 

```
privateKey, _ := ecdsa.GenerateKey(crypto.S256(), rand.Reader)
```

**Comment by ashish10677** [comment]
Can't we just generate a random key now?

**Comment by Yashk767** [comment]
> Can't we just generate a random key now?

Actually we can, I went through the new updates there is a panic with the error shown in issue description if the curve instance is not of curve `secp256k1`. So on changing the curve paramater in `ecdsa.GenerateKey()` to `crypto.S256()` instead of `elliptic.P256()` it works. 
Updated the issue description and raised a PR #1120 for the same.
