### ISSUE TITLE
Update go-ethereum version to `1.12.2`  instead of `1.12.0`

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#1128]
#### Description

The dependabot was throwing an alert `Go-Ethereum vulnerable to denial of service via malicious p2p message`.
Even after updating go-ethereum version to `1.12.0` it is still vulnerable to same alert.

Checking here - https://github.com/razor-network/oracle-node/security/dependabot/75, it is suggesting to use go ethereum stable version `1.12.1` or later.

The latest stable release is `go-ethereum 1.13.0` but for this release there is a disclaimer that `it is production ready but its not tested by any external projects yet` so the next stable is `go-ethereum 1.12.2` that we can use.

So updating to `go-ethereum 1.12.2` will remove the alert.

**Comment by Yashk767** [comment]
Currently `v1.0.7` is on `go ethereum1.12.0`  , as the dependabot alert is throwing a vulnerability error should we update again? @SkandaBhat @ashish10677

**Comment by ashish10677** [comment]
We cannot update to an unstable/non-production ready version. I think for the time being we should keep it as 1.12 and test. Once go ethereum's next stable version is released then we can upgrade to that version.

**Comment by Yashk767** [comment]
> We cannot update to an unstable/non-production ready version. I think for the time being we should keep it as 1.12 and test. Once go ethereum's next stable version is released then we can upgrade to that version.

go-ethereum `1.12.2` is a stable release it seems - https://github.com/ethereum/go-ethereum/releases/tag/v1.12.2
