### ISSUE TITLE
IF condition should be placed before calculating transaction options.

### ISSUE THREAD

**Issue by ashish10677** [razor-network/oracle-node#826]
#### System information
- **OS & Version**: MacOS
- **Go version:** `go version go1.17.6 darwin/arm64`
- **razor-go version:** `v1.1.2-internal-testnet`

#### Describe the bug
https://github.com/razor-network/razor-go/blob/982502c3c715b86483809aa99d303f4afc7144ad/cmd/dispute.go#L176
This if condition should be placed above 
https://github.com/razor-network/razor-go/blob/982502c3c715b86483809aa99d303f4afc7144ad/cmd/dispute.go#L168
because we are unnecessarily calculating txnOpts, even if there is no dispute to reset.

**Comment by Yashk767** [comment]
This was reopened in order to merge v1-audit changes to `v1.0.6`.
But this issue is covered in GiveSorted fixes, which was done in `v1.0.4` release. So can be closed now.
