### ISSUE TITLE
Use `filepath.join` instead of `path.join`

### ISSUE THREAD

**Issue by ashish10677** [razor-network/oracle-node#884]
`path.Join(...)` always joins using a forward slash. This may cause issues in windows or other systems using a different delimiter. Use `filepath.Join(...)` instead which uses os specific path separators.

This has to be done in:
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/create.go#L47
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/import.go#L56
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/listAccounts.go#L45
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/vote.go#L315
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L16
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L32
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L40
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L55
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L64
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L82
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L98
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L114

**Comment by Handschrift** [comment]
If you like you can assign this issue to me and I will take a look later

**Comment by ashish10677** [comment]
> If you like you can assign this issue to me and I will take a look later

Sure @Handschrift
