### ISSUE TITLE
Add ETA for unlockWithdraw

### ISSUE THREAD

**Issue by Yashk767** [razor-network/oracle-node#885]

**Comment by shyam-patel-kira** [comment]
ETA for what exactly is needed here @Yashk767 ?

**Comment by Yashk767** [comment]
There is a unLockWithdraw lock after Initiatewithdraw. 
You have to display the ETA for that lock period to get over.

You can refer this PR https://github.com/razor-network/razor-go/pull/622 which solves the same issue.
