### ISSUE TITLE
giveSorted fixes

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/oracle-node#911]
#### Describe the bug
Once givesorted tx is confirmed, the next givesorted should know where it has to start from. 

#### Expected behaviour

- [x] if there is no need of givesorted it should not call it.

- [x] if prev giveSorted was incorrect, then reset dispute and start again.

- [ ] if prev giveSorted was correct, do not call giveSorted again. even if finalize dispute fails.

https://razorscan.io/tx/0xb962064a6f3d3a76852dc0e9c94f1943e015908e0e76628e4ea4053dde551575

https://razorscan.io/tx/0x2cade48c0cc69e7180b17bf870a68fee827243e4937933c534bc6440578c5f05

- [x] if one of the givesorted fails, then reset and try again (in recursion)
- [x] If govesorted fails, do not call finalizeDispute

#### Steps to reproduce the behaviour

Run 2 nodes, the other node tries to give Sorted.

- [x] Scenario 1: giveSorted goes thru in 1 go
- [x] Scenario 2: giveSorted exceeds gas limit, is split into multiple calls and executed sequentially
- [x] Scenario 3: giveSorted exceeds gas limit, but one of the calls fails.
//	eg: chunks of 10, among 100. Here if first chunk fails, then second onwards should not be called. This does not happen.

- [x] Scenario 4: redundant nodes run giveSorted. 
// a. giveSorted chunk is called by first node a and succeeds.
// b. node b is not aware of this, and calls giveSorted for the same chunk, and the transaction fails.
// c. node b thinks it is an invalid giveSorted, and calls resetDispute.
// d. node a is not able to finalise dispute because it was reset by node b. 

- [x] Scenario 5: node is restarted in dispute state.
// Currenlty, giveSorted is called again for all. If giveSorted is called previously, then resetDispute is called.

- [x]  Scenario 6: node a does giveSorted but tx is pending
// if tx is not confirmed, node b also does giveSorted
// node b's tx fails. node a's tx is successful.
// Since we are validating giveSorted from the blockchain, node b will not call ResetDispute.

- [x] Scenario 7: onchain state is invalid and both nodes call resetDispute at the same time.
// node a: resetDispute (n: 1), giveSorted (n: 2)
// node b: resetDispute (n: 2), giveSorted (n: 3)

- [ ]  Scenario 8: node a givesSorted for block 1, node b does the same for block 7
// node should check on chain state and should not continue dispute for block 7 when block on is ongoing. It should continue dispute for block 1.
// node b will end up never disputing for block 7. we should recheck for disputes multiple times in the state.

// Solution:
- [x]  1. calculate nonce from confirmed transactions and not pending transactions
- [x]  2. Validate disputes status before every dispute-related call.-

The index of the smallest sorted values should be greater to your LVV.

- [] a. node should be aware of dispute status. If the block is already disputed, then we should not go thru with dispute.
- [x]  b. node should be aware of ongoing dispute, and continue it.
- [x]  3. Repeat dispute calculation off chain multiple times throughout dispute state.

fetch from disputes struct: https://github.com/razor-network/oracle-contracts/blob/master/contracts/Core/storage/BlockStorage.sol#L7

**Comment by Yashk767** [comment]
>>> if prev giveSorted was correct, do not call giveSorted again. even if finalize dispute fails.

giveSorted scenario - 
- We iterate through the proposed blocks and check for dispute case in each block.
- If there is a `medians not matching` dispute case, we call giveSorted. 
- If giveSorted goes through we call FinalizeDispute.
- If FinalizeDispute fails we resetDispute and move on to check dispute for next block.
- We don't call giveSorted again for the same proposed block even when finalizeDispute fails.

**Comment by SkandaBhat** [comment]
// Scenario 4: redundant nodes run giveSorted. 
// a. giveSorted chunk is called by first node a and succeeds.
// b. node b is not aware of this, and calls giveSorted for the same chunk, and the transaction fails.
// c. node b thinks it is an invalid giveSorted, and calls resetDispute.
// d. node a is not able to finalise dispute because it was reset by node b.

**Comment by Yashk767** [comment]
>>>> Scenario 8: node a givesSorted for block 1, node b does the same for block 7
// node should check on chain state and should not continue dispute for block 7 when block one is ongoing. It should continue dispute for block 1.

For this scenario of running redundant nodes, we are checking for the ongoing dispute with the help of `leafId`

CONDITION -
````
	if disputesMapping.LeafId != leafId {
		return errors.New("another giveSorted in progress")
	}
        if disputesMapping.LastVisitedValue.Cmp(sortedValues[0]) < 0 {
                 PERFORM GIVESORTED
        }
````

Case A -  When leaf ids are different for both blocks (Works fine)

if node A disputing for block 1 on leafId = 1. 
While node B raised dispute for block 7 on leafId = 2.

Assuming node A has done giveSorted first, 
so, disputesMapping.LeafId = 1

node B starts giveSorted on leafId = 2, but fails as `disputesMapping.LeafId != leafId B`. So we will do the dispute for block 7 after 1st dispute completes.

CASE B - node A and node B both dispute together on same leafId from different blocks. (Problem)

node A disputes block 1 on leafid 1
node B disputes block 7 on leafid 1.

As here leafId is same. I cannot check the ongoing dispute as we dont record blockId in disputes mapping. We only have leafId for checking dispute in progress

**Comment by Yashk767** [comment]
New Solution :

- If a staker is running a backup node, we will provide an optional general flag `backupNode` which would not allow staker to perform `medians dispute`
- if its a `gas limit reached` error, perform the linear recursion as mentioned below,
```def giversorted(start, len)
while() {
  if(len==nil) len=len(list)
  try {
  givesorted(start, len)
  } catch(gaserror)
  { 
  len/=2
  givesorted(start, len)
  }
  givesorted(start+len, len)
}
```

@SkandaBhat @hrishikeshio @ashish10677
