### ISSUE TITLE
If RPC is unreachable during running vote command, no error is logged.

### ISSUE THREAD

**Issue by ashish10677** [razor-network/oracle-node#936]
#### System information

- **OS & Version**: MacOS
- **Go version:** `go1.17.6 darwin/arm64`
- **razor-go version:** `1.0.0-mainnet stable`

#### Describe the bug
If razor-go is not connected to the internet, and vote command is started, it logs and throws error. But if the user is already voting and in between if there is no internet or RPC is unreachable, nothing is logged. Razor-go becomes stagnant.

#### Expected behaviour
`razor-go` must throw error logs if RPC is unreachable.

#### Actual behaviour
`razor-go` logs nothing.

#### Steps to reproduce the behaviour
1. Start vote command with internet connection.
2. In between turn off the internet.

#### Backtrace
```
{"level":"info","msg":"Block: 321079 Epoch: 1385545 State: -1 Staker ID: 16 Stake: 1172931.560059 sRZR Balance: 113212.859283 Eth Balance: 2.089558","time":"2022-09-08T16:36:34Z"}
{"level":"error","msg":"Error in fetching logs.... Retrying","time":"2022-09-08T16:45:03Z"}
```
For 9 minutes nothing was logged.

**Comment by Yashk767** [comment]
If the node is not connected to the internet, any of the client function itself throws a timeout case after few minutes. (timeout duration is variable)
<img width="1381" alt="Screenshot 2022-09-09 at 1 04 50 PM" src="https://user-images.githubusercontent.com/76935991/189317484-eacb2697-5be3-40b9-a768-4e1735fca173.png">.

**Comment by Yashk767** [comment]
Similarly, every contract call is dependent on client connection. Same error and timeout case is observed.

We need to have a discussion on how to have a timeout implemented on every contract call?
@ashish10677  @SkandaBhat 
![image](https://user-images.githubusercontent.com/76935991/189318490-f1e1d6bd-1bb6-44ac-8c81-ef26b0da1d05.png)

**Comment by SkandaBhat** [comment]
Need to refactor entire codebase to utilize wrapper.
