### ISSUE TITLE
Razor go documentation to be updated with restart policy and restart command

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/oracle-node#942]
- [ ] Update vote command with `docker run...`
- [ ] Mention in the docs about risks of supplying a password and tell the user how to delete the command from history
- [ ] Mention `backupNode` flag info in vote command.

**Comment by Yashk767** [comment]
Can close this @SkandaBhat . Created this issue in `docs-v2` repo - https://github.com/razor-network/docs-v2/issues/64
